name: Sahil Pipline

on:
    push:
     branches: [prac1]

jobs:
    Checkout:
        name: Checkout Stage
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4

    Setup:
        name: Setup Stage
        runs-on: ubuntu-latest
        needs: Checkout
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4
        -   name: SetUp Pyton Environment
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'

    UnitTest:
        name: Unit Test Stage
        runs-on: ubuntu-latest
        needs: Setup
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4
        -   name: Unit Test
            run: echo "Unit Test Complite"

    Deploy:
        name: Deploy Stage
        runs-on: ubuntu-latest
        needs: UnitTest
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4
        -   name: SetUp Pyton Environment
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'
        -   name: libraries Install
            run: pip install -r requirements.txt
        -   name: Deploy
            run: |
                python app.py &
                sleep 5
                echo "App Started"

