name: Sahil Pipline

on:
    push:
     branches: [prac1]

jobs:
    Checkout:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4

        -   name: SetUp Pyton Environment
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'

        -   name: Unit Test
            run: echo "Unit Test Complite"

        -   name: libraries Install
            run: pip install -r requirements.txt

        -   name: Deploy
            run: |
                python app.py &
                sleep 5
                echo "App Started"
